### ISSUE TITLE
[Question] Random deformed FLAME mesh at texture generation

### ISSUE THREAD

**Issue by yjhong89** [shivangi-aneja/ClipFace#1]
Dear authors, 
Thanks for sharing great work!

I wonder what kind of random deformations are applied to FLAME mesh when generating texture.  (M_rand in below figure)
![image](https://user-images.githubusercontent.com/26890721/215014175-bd2426ef-0a9e-4ece-8ff9-b653ad1820b1.png)

- I guess it is randomly perturbing expression vectors while other vectors (shape, pose) are maintained same
- Is it important  for good visual quality of UV map ? 
- When is the code supposed to release ?

Thanks you.
YJHong.

**Comment by shivangi-aneja** [comment]
Hi,
The applied deformations include expression, shape, and pose codes extracted from FFHQ images using DECA.
Yes, it is critical to apply these deformations during StyleGAN training to generate realistic UV maps.

We plan to release the code in early May
